name: Extract WordPress Hooks

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.php'
      - 'extract-wp-hooks.json'
      - '.extract-wp-hooks.json'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.php'
      - 'extract-wp-hooks.json'
      - '.extract-wp-hooks.json'
  workflow_dispatch:

jobs:
  extract-hooks:
    runs-on: ubuntu-latest
    name: Extract and document WordPress hooks
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Extract WordPress hooks
      uses: akirk/extract-wp-hooks@main
      with:
        # Optional: specify custom config file location
        # config-file: 'my-custom-config.json'
        
        # Optional: specify custom wiki repository
        # wiki-repo: 'username/my-project.wiki.git'
        
        # Optional: exclude additional directories
        # exclude-dirs: 'vendor,node_modules,tests'
        
        # Optional: ignore specific filter names
        # ignore-filters: 'debug_filter,internal_hook'